version: "3.0"

services:
  django-api:
    build: .
    depends_on:
      - psql
    env_file:
      - .env_django
    ports:
      - "8090:8000"
    volumes:
      - .:/testFlink
  psql:
    image: postgres
    volumes:
      - pg_volume:/var/lib/postgresql
    env_file:
      - .env_db
    ports:
      - "5492:5432"
volumes:
  pg_volume:
    external: true