apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  EMAIL_SERVER: "smtp.sendgrid.net"
  FINANCIAL_API_KEY: "apikey"
  ENVIRONMENT: "development"
  PG_DATABASE: "test_flink"
  PG_USER: "test_flink"
  PG_PORT: "5432"
  PG_HOST: "psql"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: psql-config
data:
  POSTGRES_DATABASE: "test_flink"
  POSTGRES_USER: "test_flink"
