# Generated by Django 4.1.3 on 2022-11-07 09:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_market_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='market_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True), size=50),
        ),
    ]
